export {default as StakePg} from "./StakePg/StakePg";
export {default as AccountPg} from "./AccountPg/AccountPg";
export {default as DashboardPg} from "./DashboardPg/DashbaordPg";
export {default as DepositPg} from "./DepositPg/DepositPg";
export {default as HistoryPg} from "./HistoryPg/HistoryPg";
export {default as PurchaseCryptoPg} from "./PurchaseCryptoPg/PurchaseCryptoPg";
export {default as SubscriptionPg} from "./SubscriptionPg/SubscriptionPg";
export {default as SupportPg} from "./SupportPg/SupportPg";
export {default as TradExpertPg} from "./TradExpertPg/TradExpertPg";
