export {default as coindash} from "./coin.jpg";
export {default as emptyboxdash} from "./empty-box.jpg";
export {default as increasebar} from "./increase.jpg";
export {default as moneybar} from "./money.jpg";
export {default as profilebar} from "./profile.jpg";
export {default as veraccount} from "./veraccount.jpg";
export {default as walletbar} from "./wallet.jpg";
export {default as withdrawbar} from "./withdraw.jpg";
export {default as optionswizardimg} from "./copy-6.jpg";
export {default as protraderximg} from "./IMG-20250627-WA0006.jpg";
export {default as cryptoxavantimg} from "./copy-9.jpg";
export {default as sambatraderimg} from "./copy-10.jpg";
export {default as swingkingimg} from "./copy-13.jpg";
export {default as swingmasterimg} from "./IMG-20250627-WA0007.jpg";
export {default as forexempressimg} from "./copy-trader-1.jpg";
export {default as optionsproimg} from "./IMG-20250627-WA0002.jpg";
export {default as quantumasterimg} from "./copy-trader-3.jpg";
export {default as cryptomasterimg} from "./copy-trader-4.jpg";
export {default as daytradequeenimg} from "./copy-trader.jpg";
export {default as forexqueenximg} from "./copy.jpg";
export {default as jbravoimg} from "./IMG-20250627-WA0003.jpg";
export {default as elonmuskimg} from "./IMG-20250627-WA0004.jpg";
export {default as rosscameron} from "./IMG-20250627-WA0005.jpg";
export {default as BTCoin} from "./BTC.svg";
export {default as ADACoin} from "./ADA.svg";
export {default as ETHCoin} from "./ETH.svg";
export {default as SOLCoin} from "./SOL.svg";
export {default as TRXCoin} from "./TRX.svg";
export {default as USDTCoin} from "./USDT.svg";
export {default as DOGECoin} from "./DOGE.svg";
export {default as AppleStock} from "./AAPL.svg";
export {default as AdobeStock} from "./ADBE.svg";
export {default as GoogleStock} from "./GOOGL.svg";
export {default as NetflixStock} from "./NFLX.svg";
export {default as NikeStock} from "./NFLX.svg";
export {default as TelsaStock} from "./TSLA.svg";
export {default as AmazonStock} from "./AMZN.svg";
export {default as tradeHome} from "./trade.webp";
// export {default as encIncImg} from "https://res.cloudinary.com/dr6a80sph/image/upload/v1744201967/zztjltjtroomo0kkjaye.webp";
export {default as heroImg} from "./mock-up-copy-space-pretty-brazilian-or-hispanic-2024-04-23-02-10-38-3-e1717138224410.png";
export {default as wwoImg3} from "./Anonymous-Transaction-4.png";
export {default as wwoImg4} from "./Secure-Trading-5.png";
export {default as wwoImg5} from "./Trading-6.png";
export {default as wwoImg6} from "./Market-Trading-Analytics-2.png";
export {default as ourvalueImg} from "./two-stock-exchange-traders-getting-profit-in-trading-currency-stock--1536x1022.jpg";
export {default as authImg} from "./login-dark-Bhn1kr2d.png";
export {default as authImag} from "./login-index-CHtk99ek.png";
export {default as herobgone} from "./aset-homepage-2.png";
export {default as herobgtwo} from "./aset-homepage-4.png";
export {default as wwaImg} from "./two-traders-brokers-stock-exchange-market-investors-discussing-crypto-trading-.jpg";
export {default as aboutusOne} from "./about-us-1.png";
export {default as aboutusTwo} from "./about-us-2.png";
// export {default as curplanImg} from "";
export {default as planbonusImg} from "./coin (1).jpg";
export {default as paypalImg} from "./paypal.jpg";
export {default as zelleImg} from "./zelle.jpg";
export {default as cashappImg} from "./cashapp.jpg";
export {default as venmoImg} from "./venmo.jpg";
export {default as bankwithdrawalImg} from "./bank-withdrawal.svg";
// export {default as custoneImg} from "";
export {default as custwoImg} from "./miltiadis-fragkidis-ub21SU8DA_8-unsplash.jpg";
export {default as CHFJPYImg} from "./CHFJPY (1).svg";
export {default as EURJPYImg} from "./EURJPY (1).svg";
export {default as AUDUSDImg} from "./AUDUSD (1).svg";
export {default as EURGBPImg} from "./EURGBP (1).svg";
export {default as USDCADImg} from "./USDCAD (1).svg";
export {default as premiummimg} from "./premiumm.webp";
export {default as silverrimg} from "./silverr.webp";
export {default as goldimg} from "./gold.webp";
export {default as bronzeimg} from "./bronze.webp";
export {default as binancelogo} from "./binance.webp";
export {default as bitsologo} from "./bitso.webp";
export {default as coinbaselogo} from "./coinbase.webp";
export {default as moonpaylogo} from "./moonpay.gif";
export {default as CardAssetsImg} from "./Card-Assets-3.png";
export {default as TopAset2Img} from "./top-aset-2.png";
export {default as expltradefx} from "./leaf.png";
export {default as expltradecpt} from "./a-lab.png";
export {default as expltradequit} from "./aven.png";
// export {default as expltradestk} from "";
export {default as expltradeetf} from "./kyan.png";
export {default as expltradecom} from "./treva.png";
export {default as playstoreImg} from "./mock-up-copy-space-pretty-brazilian-or-hispanic-2024-04-23-02-10-38-3-e1717138224410.png";
export {default as applestoreImg} from "./Asset-4@300x-8-2048x620 (1).png";
export {default as gplaystoreImg} from "./Asset-3@300x-8-2048x620 (1).png";
export {default as microsoftImg} from "./Microsoft-White-2048x620 (1).png";
export {default as HomeLogo} from "./Homelogo.png";
export {default as istockman} from "./istockman.jpg";
export {default as metamaskimg} from "./metamask@2x.png";
export {default as paypalimg} from "./paypal-2.png";
export {default as trustwallimg} from "./trust@2x.png";
export {default as universalimg} from "./universal@2x.png";
export {default as mastercardimg} from "./mastercard.png";
export {default as okxlogoimg} from "./OKX_logo@2x.png";
export {default as alogoimg} from "./Frame 5545-1.png";
export {default as uniswapimg} from "./uniswap@2x.png";
export {default as singaporeflag} from "./flag-for-singapore_1f1f8-1f1ec.png";
export {default as franceflag} from "./download (3).png";
export {default as czechflag} from "./download (4).png";
export {default as germanyflag} from "./download (1).jpg";
export {default as UAEFlag} from "./download (5).png";
export {default as traderone} from "./1000435582.jpg";
export {default as tradertwo} from "./1000435585.jpg";
export {default as traderthree} from "./1000435587.jpg";
export {default as traderfour} from "./1000435995.jpg";
export {default as traderfive} from "./1000435996.jpg";
export {default as tradersix} from "./1000435997.jpg";
